[package]
name = "rhp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
async-stream = "0.3"
axum = { version = "0.8.9", features = ["macros", "ws"] }
axum-test = { version = "21.0.0", features = ["ws"] }
uuid = { version = "1", features = ["v4"] }
clap = { version = "4.6.6", features = ["derive", "env"] }
dotenv = "0.15.0"
serde = "1.0.229"
serde_json = "1.0.151"
serde_urlencoded = "0.7.1"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
notify = "8"
tower-http = { version = "0.7", features = ["fs", "trace"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
sqlx = { version = "0.9", default-features = false, features = [
    "runtime-tokio",
    "any",
    "postgres",
    "sqlite",
    "macros",
]}
rquickjs = { version = "0.12.2", features = ["macro", "classes", "futures", "parallel"] }
